server:
  port: 8761

eureka:
    server:
        renewal-percent-threshold: 0.85
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: service-registry
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false